spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/indicafilmes-teste
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
logging:
  level:
    com.example.indicafilmes: DEBUG

tmdb:
  api-key: test-tmdb-key
  base-url: https://api.themoviedb.org/3

admin:
  api-key: test-admin-key
